1. Попробуйте изменить параметры нейронной сети, работающей с датасетом imdb, либо нейронной сети, работающей airline-passengers (она прилагается вместе с датасетом к уроку в виде отдельного скрипта) так, чтобы улучшить её точность. Приложите анализ

In [1]:
import numpy as np
from keras.utils.data_utils import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, Dropout
from keras.layers import LSTM
from keras.datasets import imdb

In [2]:
max_features = 10_000

# обрезаем тексты после данного количества слов (среди top max_features наиболее используемые слова)
maxlen = 80
batch_size = 50 # увеличьте значение для ускорения обучения

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=max_features)

17464789/17464789 [==============================] - 0s 0us/step


In [3]:
[len(i) for i in X_train[:5]]

[218, 189, 141, 550, 147]

In [4]:
print(X_train[:5])

[list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32])
 list([1, 194, 1153, 194, 8255, 78, 228, 5, 6, 1463, 

In [5]:
index2word = {v:k for k, v in imdb.get_word_index().items()}

for idx_word in X_train[0]:
    print(index2word[idx_word], end=' ')

1641221/1641221 [==============================] - 0s 0us/step
the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room and it so heart shows to years of every never going and help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but and to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other and in of seen over landed for anyone of and br show's to whether from than out themselves history he name half some br of and odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while histor

In [6]:
print('Pad последовательности (примеров в x единицу времени)')
X_train = pad_sequences(X_train, maxlen=maxlen)
X_test = pad_sequences(X_test, maxlen=maxlen)
print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)

Pad последовательности (примеров в x единицу времени)
X_train shape: (25000, 80)
X_test shape: (25000, 80)


In [7]:
X_train[0]

array([  15,  256,    4,    2,    7, 3766,    5,  723,   36,   71,   43,
        530,  476,   26,  400,  317,   46,    7,    4,    2, 1029,   13,
        104,   88,    4,  381,   15,  297,   98,   32, 2071,   56,   26,
        141,    6,  194, 7486,   18,    4,  226,   22,   21,  134,  476,
         26,  480,    5,  144,   30, 5535,   18,   51,   36,   28,  224,
         92,   25,  104,    4,  226,   65,   16,   38, 1334,   88,   12,
         16,  283,    5,   16, 4472,  113,  103,   32,   15,   16, 5345,
         19,  178,   32], dtype=int32)

In [8]:
X_test[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    1,  591,  202,   14,   31,    6,  717,   10,   10,    2,
          2,    5,    4,  360,    7,    4,  177, 5760,  394,  354,    4,
        123,    9, 1035, 1035, 1035,   10,   10,   13,   92,  124,   89,
        488, 7944,  100,   28, 1668,   14,   31,   23,   27, 7479,   29,
        220,  468,    8,  124,   14,  286,  170,    8,  157,   46,    5,
         27,  239,   16,  179,    2,   38,   32,   25, 7944,  451,  202,
         14,    6,  717], dtype=int32)

In [9]:
index = imdb.get_word_index()
len(index)

88584

In [10]:
np.max(X_train)

9999

# Bag of Word

In [11]:
def vectorize(sequences, dimension=10_000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1
    return results

X_train_bow = vectorize(X_train, dimension=max_features)
X_test_bow = vectorize(X_test, dimension=max_features)

In [12]:
X_train_bow.shape

(25000, 10000)

In [13]:
X_train_bow[0:, :10]

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 1., 1.],
       [0., 0., 1., ..., 1., 1., 1.]])

Построим модель

In [14]:
model_bow = Sequential()

model_bow.add(Dense(128, activation='relu', input_shape=(max_features, )))
model_bow.add(Dense(1, activation='sigmoid'))

# стоит попробовать использовать другие оптимизаторы и другие конфигурации
model_bow.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
model_bow.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               1280128   
                                                                 
 dense_1 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1,280,257
Trainable params: 1,280,257
Non-trainable params: 0
_________________________________________________________________


Обучение модели

In [15]:
model_bow.fit(X_train_bow[:], y_train[:],
              batch_size=batch_size,
              epochs=3,
              validation_data=(X_test_bow, y_test))

Epoch 1/3
500/500 [==============================] - 16s 30ms/step - loss: 0.4015 - accuracy: 0.8164 - val_loss: 0.3616 - val_accuracy: 0.8373
Epoch 2/3
500/500 [==============================] - 16s 32ms/step - loss: 0.2574 - accuracy: 0.8910 - val_loss: 0.3934 - val_accuracy: 0.8274
Epoch 3/3
500/500 [==============================] - 13s 26ms/step - loss: 0.1717 - accuracy: 0.9334 - val_loss: 0.4456 - val_accuracy: 0.8237


Валидация модели

In [16]:
score, acc = model_bow.evaluate(X_test_bow, y_test, batch_size=batch_size)

500/500 [==============================] - 4s 7ms/step - loss: 0.4456 - accuracy: 0.8237


Обучение на последовательности

In [17]:
def vectorize_seq(sequences, xLen=100):
    results = np.zeros((len(sequences), xLen, 1))
    for i, sequence in enumerate(sequences):
        for j in range(xLen):
            results[i, j,:] = sequence[j]
    return results

X_train_seq = vectorize_seq(X_train, xLen=maxlen)
X_test_seq = vectorize_seq(X_test, xLen=maxlen)

In [18]:
X_test.shape, X_test_seq.shape

((25000, 80), (25000, 80, 1))

In [19]:
display(X_train[0, :10], X_train_seq[0, :10])

array([  15,  256,    4,    2,    7, 3766,    5,  723,   36,   71],
      dtype=int32)

array([[1.500e+01],
       [2.560e+02],
       [4.000e+00],
       [2.000e+00],
       [7.000e+00],
       [3.766e+03],
       [5.000e+00],
       [7.230e+02],
       [3.600e+01],
       [7.100e+01]])

Построение модели

In [20]:
model = Sequential()
model.add(LSTM(128, input_shape=(maxlen, 1)))
model.add(Dense(1, activation='sigmoid'))

# стоит попробовать использовать другие оптимизаторы и другие конфигурации
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 128)               66560     
                                                                 
 dense_2 (Dense)             (None, 1)                 129       
                                                                 
Total params: 66,689
Trainable params: 66,689
Non-trainable params: 0
_________________________________________________________________


Процесс обучения

In [21]:
model.fit(X_train_seq, y_train,
          batch_size=1000,
          epochs=5,
          validation_data=(X_test_seq, y_test))

Epoch 1/5
25/25 [==============================] - 51s 2s/step - loss: 0.7011 - accuracy: 0.5090 - val_loss: 0.6909 - val_accuracy: 0.5266
Epoch 2/5
25/25 [==============================] - 48s 2s/step - loss: 0.6900 - accuracy: 0.5344 - val_loss: 0.6889 - val_accuracy: 0.5396
Epoch 3/5
25/25 [==============================] - 39s 2s/step - loss: 0.6878 - accuracy: 0.5420 - val_loss: 0.6865 - val_accuracy: 0.5469
Epoch 4/5
25/25 [==============================] - 39s 2s/step - loss: 0.6865 - accuracy: 0.5448 - val_loss: 0.6892 - val_accuracy: 0.5380
Epoch 5/5
25/25 [==============================] - 48s 2s/step - loss: 0.6847 - accuracy: 0.5544 - val_loss: 0.6851 - val_accuracy: 0.5516


Валидация модели

In [22]:
score, acc = model.evaluate(X_test_seq, y_test, batch_size=batch_size)

500/500 [==============================] - 26s 51ms/step - loss: 0.6851 - accuracy: 0.5516


# Embedding
Сеть обучилась не очень хорошо, попробуем использовать эмбединги (векторное представление слов)

In [23]:
model = Sequential()
model.add(Embedding(max_features, 128))

In [24]:
model.predict(X_train[:1])

1/1 [==============================] - 0s 98ms/step


array([[[ 0.00053264,  0.00280992, -0.01371355, ..., -0.03208148,
          0.04791012,  0.04338063],
        [-0.04556995, -0.00722599, -0.00829094, ...,  0.02314743,
         -0.02283702, -0.03853351],
        [-0.03946695,  0.01515568, -0.02263357, ..., -0.01271365,
         -0.03176667,  0.04170448],
        ...,
        [ 0.02767596,  0.02314377, -0.03306659, ..., -0.02115984,
          0.04225365, -0.01397163],
        [ 0.01130091,  0.00128198, -0.00617618, ..., -0.01216936,
         -0.00332023,  0.02798034],
        [-0.01409321,  0.03967512, -0.04798733, ...,  0.01071952,
          0.01599154, -0.00113124]]], dtype=float32)

In [25]:
model.predict(X_train[:1]).shape

1/1 [==============================] - 0s 23ms/step


(1, 80, 128)

Построение модели

In [26]:
model = Sequential()
model.add(Embedding(max_features, 128))
model.add(Dropout(0.3))
model.add(LSTM(128, dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 128)         1280000   
                                                                 
 dropout (Dropout)           (None, None, 128)         0         
                                                                 
 lstm_1 (LSTM)               (None, 128)               131584    
                                                                 
 dense_3 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1,411,713
Trainable params: 1,411,713
Non-trainable params: 0
_________________________________________________________________


Обучение модели

In [27]:
model.fit(X_train, y_train,
          batch_size=128,
          epochs=3,
          validation_data=(X_test, y_test))

Epoch 1/3
196/196 [==============================] - 117s 587ms/step - loss: 0.4520 - accuracy: 0.7806 - val_loss: 0.3518 - val_accuracy: 0.8453
Epoch 2/3
196/196 [==============================] - 94s 478ms/step - loss: 0.2925 - accuracy: 0.8792 - val_loss: 0.3629 - val_accuracy: 0.8392
Epoch 3/3
196/196 [==============================] - 114s 581ms/step - loss: 0.2400 - accuracy: 0.9030 - val_loss: 0.4240 - val_accuracy: 0.8322


Валидация модели

In [28]:
score, acc = model.evaluate(X_test, y_test, batch_size=batch_size)

500/500 [==============================] - 33s 66ms/step - loss: 0.4240 - accuracy: 0.8322
